using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using DG.Tweening;


public class Player : MonoBehaviour
{
    // ï¿½Zï¿½[ï¿½uï¿½pï¿½Ì“ï¿½ï¿½ÍÈ—ï¿½
    private SaveSystem System => SaveSystem.Instance;
    private MainShipData Data => System.MainShipData;
    // ï¿½ï¿½ï¿½ÌƒXï¿½Nï¿½ï¿½ï¿½vï¿½gï¿½Qï¿½Æ—p
    public SP_Bullet sp_Bullet;
    public CreateShip createcs;
    public CoolDown CoolDownScript;
    // Playerï¿½ï¿½ï¿½
    public float speed;
    public  int Player_HP = 60;
    public static int MaxHP;
    public Slider hp_slider;
    public bool isTurn = false;
    public static float ScoreHP;
    private bool isSecond;
    public int Defence;
    // ï¿½eï¿½Ìï¿½ŞAï¿½ï¿½ï¿½ËˆÊ’u
    [SerializeField] private GameObject[] Bullet;
    [SerializeField] private GameObject bulletPoint;
    public GameObject[] Clones = new GameObject[256];
    private GameObject P_Bullet;
    // ï¿½oï¿½ßï¿½ï¿½Ôæ“¾ï¿½pï¿½Ïï¿½
    [SerializeField] private float _timeInterval;
    private float _timeElapsed;
    // ï¿½}ï¿½Eï¿½Xï¿½zï¿½Cï¿½[ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½æ“¾ï¿½pï¿½Ïï¿½
    private float MousWheel;
    // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½pï¿½iï¿½[ï¿½Ïï¿½
    [SerializeField]private float[] sp_Range = new float[4];
    public int BulletSelect;   
    public List<bool> Reload = new List<bool>();
    // ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Ïï¿½
    private bool DamageHit;
    // ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½p
    [SerializeField] private Animator SP_Anim;

    private bool shotcheck;

    public float _anglePerFrame = 0.1f;
    [SerializeField] private Material skybox;
    private Vector3 vec;

    public static Player instance;

    public ParticleSystem JetEffect;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
        }
    }

    void Start()
    {
        //skybox.SetVector("_Rotation", new Vector3(1, 0, 0));
        //skybox.SetVector("_Speed", new Vector3(0, 0, 0));
        //vec = new Vector3(1, 0, 0);

        ScoreHP = 0;

        Player_HP = Data.HP;

        // ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        hp_slider.maxValue = Player_HP;
        
        hp_slider.value = Player_HP;
        for (int i = 0; i < 4; i++)
        {
            speed += createcs.SPD[i];
        }


        SP_Anim.GetComponent<Animator>();

        // Listï¿½Éï¿½ï¿½ï¿½Ç‰ï¿½(ture:ï¿½ï¿½ï¿½Ë‰Â”\ï¿½Afalse:ï¿½Nï¿½[ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½)
        Reload.Add(true);   // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½1
        Reload.Add(true);   // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½2
        Reload.Add(true);   // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½3
        Reload.Add(true);   // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½4
        //Debug.Log(Reload.Count);

        // ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½p
        JetEffect.Pause();
    }

    void Update()
    {

        //skybox.SetVector("_Speed", vec);
        // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
        #region ï¿½Ú“ï¿½
        if (Input.GetKey(KeyCode.W) && isTurn == false)
        {
            transform.position += transform.forward * speed * Time.deltaTime;

            //vec = new Vector3(1, 0, 0);
            //ï¿½Gï¿½tï¿½Fï¿½Nï¿½gï¿½p
            JetEffect.Play();
        }
        //else
        //{
        //    vec = new Vector3(0, 0, 0);
        //}
        if (Input.GetKey(KeyCode.S) && isTurn == false)
        {
            transform.position -= transform.forward * speed * Time.deltaTime;
            JetEffect.Stop();
        }
        if (Input.GetKey(KeyCode.Q))
        {
            transform.position += transform.up * speed * Time.deltaTime;
        }
        if (Input.GetKey(KeyCode.E))
        {
            transform.position -= transform.up * speed * Time.deltaTime;
        }
        if (Input.GetKey(KeyCode.M))
        {
            SceneManager.LoadScene("Result");
        }
        #endregion

        // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        #region ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½
        // ï¿½}ï¿½Eï¿½Xï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½æ“¾(ï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½é‚½ï¿½Ñ‚ï¿½1ï¿½ï¿½ï¿½Â‘ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ ï¿½fï¿½tï¿½Hï¿½ï¿½ï¿½gï¿½ï¿½0)
        MousWheel += Input.GetAxis("Mouse ScrollWheel");
        MousWheel = Mathf.Floor(MousWheel);
        MousWheel = Mathf.Clamp(MousWheel, 0.0f, 4.0f);
        //SP_Anim.SetInteger("Param", (int)MousWheel);
        #endregion

        // ï¿½eï¿½ï¿½ï¿½ï¿½
        #region ï¿½eï¿½Ì”ï¿½ï¿½ï¿½
        _timeElapsed += Time.deltaTime;

        if (_timeElapsed > _timeInterval)
        {
            shotcheck = true;
            //shot();
            // ï¿½oï¿½ßï¿½ï¿½Ô‚ï¿½ï¿½ï¿½ï¿½É–ß‚ï¿½
            _timeElapsed = 0f;
        }
        #endregion
        // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½Ì’eï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ”ï¿½ï¿½Ëï¿½ï¿½ï¿½ï¿½Ö‚ÌˆÚ“ï¿½(ï¿½}ï¿½Eï¿½Xï¿½ï¿½ï¿½Nï¿½ï¿½ï¿½bï¿½Nï¿½Å”ï¿½ï¿½ï¿½)
        #region ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½İ’ï¿½p
        if (MousWheel > 0)
        {
            if (Input.GetMouseButtonDown(0))
            {

                int AnimNum = SP_Anim.GetInteger((int)MousWheel);
                BulletSelect = (int)MousWheel;
                if (Reload[BulletSelect - 1] == true)
                {
                    SpecialAttack();
                }
            }
        }
        #endregion
        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì‘Ì—Íï¿½ï¿½ï¿½
        #region HPï¿½ï¿½ï¿½ï¿½
        // HPï¿½ÌƒXï¿½ï¿½ï¿½Cï¿½_ï¿½[ï¿½ï¿½ï¿½ï¿½
        //hp_slider.value = MaxHP;
        if (hp_slider.value <= 0)
        {
            GoResult.isWin = false;
            SceneManager.LoadScene("Result");
        }
        #endregion
    }

    // ï¿½Êï¿½eï¿½ï¿½ï¿½Ëï¿½ï¿½ï¿½ï¿½Öï¿½
    public void shot()
    {
        if(shotcheck == true)
        {
            Debug.Log("ShorIN");
            //ï¿½eï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½ï¿½æ“¾
            Vector3 placePosition = this.transform.position;
            //ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½l
            Vector3 offsetGun = new Vector3(0, 0, 8);

            //ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½í‚¹ï¿½Ä’eï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
            Quaternion q1 = this.transform.rotation;
            //ï¿½eï¿½ï¿½90ï¿½xï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
            Quaternion q2 = Quaternion.AngleAxis(90, new Vector3(1, 0, 0));
            Quaternion q = q1 * q2;

            //ï¿½eï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ğ’²ï¿½
            placePosition = q1 * offsetGun + placePosition;
            //ï¿½eï¿½ï¿½ï¿½ï¿½
            P_Bullet = Instantiate(Bullet[0], bulletPoint.transform.position, transform.rotation);
            P_Bullet.tag = "P_bullet";
            shotcheck = false;
        }
    }

    // ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½(ï¿½ï¿½ï¿½ï¿½ï¿½Í”ï¿½ï¿½Ë‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½Ì’eï¿½Ìï¿½ï¿½)
    public void SpecialAttack()
    {
        // ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½nï¿½ï¿½
        CoolDownScript.SetSpecialNum();

        // ï¿½ï¿½ï¿½Å‚Ü‚Å‚Ìï¿½ï¿½Ô‚ï¿½ï¿½ï¿½
        sp_Range[BulletSelect - 1] = createcs.GetSPRange(BulletSelect - 1);
        
        // ï¿½ï¿½ï¿½ËŒï¿½falseï¿½É•ÏX
        Reload[BulletSelect - 1] = false;

        //ï¿½eï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½ï¿½æ“¾
        Vector3 placePosition = this.transform.position;
        //ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½ç‚·ï¿½l
        Vector3 offsetGun = new Vector3(0, 0, 8);

        //ï¿½ï¿½ï¿½ï¿½ÌŒï¿½ï¿½ï¿½ï¿½Éï¿½ï¿½í‚¹ï¿½Ä’eï¿½ÌŒï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        Quaternion q1 = this.transform.rotation;
        //ï¿½eï¿½ï¿½90ï¿½xï¿½ï¿½]ï¿½ï¿½ï¿½ï¿½ï¿½éˆï¿½ï¿½
        Quaternion q2 = Quaternion.AngleAxis(90, new Vector3(1, 0, 0));
        Quaternion q = q1 * q2;

        //ï¿½eï¿½ï¿½ï¿½oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê’uï¿½ğ’²ï¿½
        placePosition = q1 * offsetGun + placePosition;
        Quaternion a = Quaternion.identity;
        //ï¿½eï¿½ï¿½ï¿½ï¿½
        //Clones[BulletSelect-1] = Instantiate(Bullet[BulletSelect], bulletPoint.transform.position, transform.rotation);

        // ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½IDï¿½ï¿½Ô‚ï¿½
        Skill.instance.StartEffect(BulletSelect);

        // ï¿½^ï¿½Oï¿½ÌŠï¿½ï¿½è“–ï¿½ï¿½
        //switch (BulletSelect - 1)
        //{
        //    case 0:
        //        Clones[BulletSelect - 1].tag = "SP1";
        //        break;
        //    case 1:
        //        Clones[BulletSelect - 1].tag = "SP2";
        //        break;
        //    case 2:
        //        Clones[BulletSelect - 1].tag = "SP3";
        //        break;
        //    case 3:
        //        Clones[BulletSelect - 1].tag = "SP4";
        //        break;
        //}

        //Destroy();
    }

    public void GetSocre_HP()
    {
        ScoreHP = hp_slider.value / Player_HP * 100;
    }

    // ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½vï¿½Zï¿½ï¿½ï¿½ï¿½
    public void P_Damage(int damage)
    {
        damage = damage - Defence;  // ï¿½hï¿½ï¿½Í•ï¿½ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ï¿½
        hp_slider.value -= damage;
    }

    // BulletSelectï¿½ï¿½nï¿½ï¿½
    public int GetSpecialNum()
    {
        return BulletSelect;
    }


    // ï¿½ï¿½ï¿½Ë‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Uï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    public void Destroy()
    {
        Destroy(Clones[BulletSelect - 1], sp_Range[BulletSelect - 1]);
    }

    // ï¿½_ï¿½ï¿½ï¿½[ï¿½Wï¿½ï¿½ï¿½ï¿½pï¿½Öï¿½
    //public void OnTriggerEnter(Collider other)
    //{
    //    if (other.gameObject.tag == "E_bullet" || other.gameObject.tag == "C_bullet")
    //    {
    //        DamageHit = false;
    //        Destroy(other.gameObject);
    //        if (DamageHit == false)
    //        {
    //            Debug.Log(other.tag);
    //            P_Damage(5 - Defence);
    //            DamageHit = true;
    //        }
    //    }
    //    if (other.gameObject.tag == "E_SP")
    //    {
    //        DamageHit = false;
    //        Destroy(other.gameObject);
    //        if (DamageHit == false)
    //        {
    //            Debug.Log(other.tag);
    //            P_Damage(20);
    //            DamageHit = true;
    //        }
    //    }
    //}
}

